import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import ProductProvider from "@/components/Context";
import Login from "@/components/Login";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ProductProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          {children}
        </body>
      </html>
    </ProductProvider>
  );
}
